[package]
name = "rustls-postquantum"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rustls = { path = "../rustls", features = [ "aws_lc_rs" ]}
aws-lc-rs = { version = "1.6", features = [ "unstable" ], default-features = false }
